apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

  ## Resource for API manifests
resources:
- ../../../base/app

  ## Staging ENV config overrides
components:
  - ../../../components/staging
