apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: woodpecker-secrets
spec:
  vault:
    name: m5-automation-secrets #todo: need vault name
    object:
      name: inteliquent-secrets
      type: multi-key-value-secret # akv object type
      contentType: application/x-yaml
  output:
    secret:
      name: woodpecker-secrets # kubernetes secret name
      dataKey: Data
