apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: woodpecker-github-secrets
spec:
  vault:
    name: m5-automation-secrets # Key vault on azure
    object:
      name: github-secrets
      type: multi-key-value-secret # akv object type
      contentType: application/x-yaml
  output:
    secret:
      name: woodpecker-github-secrets # kubernetes secret name
      dataKey: Data
