apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: woodpecker-test-docker-pkg-github-com-registry-secret
spec:
  vault:
    name: m5-automation-secrets # Key vault on azure
    object:
      name: docker-pkg-github-com-registry-secret
      type: secret # akv object type
      contentType: application/x-json
  output:
    secret:
      name: woodpecker-test-docker-pkg-github-com-registry-secret # kubernetes secret name
      type: kubernetes.io/dockerconfigjson