apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: woodpecker-test-shared-secrets
spec:
  vault:
    name: m5-automation-secrets # Key vault on azure
    object:
      name: common-secrets
      type: multi-key-value-secret # akv object type
      contentType: application/x-yaml
  output:
    secret:
      name: woodpecker-test-shared-secrets # kubernetes secret name
      dataKey: Data
