clone:
  git:
    image: woodpeckerci/plugin-git
    when:
      event: 
        - pull_request
        - deployment
        - tag

pipeline:
  dependencies:
    image: golang:1.18
    commands:
      - go mod vendor
    when: 
      event: pull_request

  publish-PR-container:
    image: plugins/docker
    group: docker
    settings:
      dry_run: false
      repo: ghcr.io/${CI_REPO}
      registry: ghcr.io
      dockerfile: Dockerfile.multistage
      platforms: linux/amd64
      build_args:
        - VERSION=PR-${CI_COMMIT_PULL_REQUEST=${CI_COMMIT_SHA:0:6}}
        - SERVICE=${CI_REPO_NAME}
        - GITHUB_LOGIN=${GITHUB_USERNAME}
        - GITHUB_PASSWORD=${GITHUB_TOKEN}
      username:
        from_secret: github_username
      password: 
        from_secret: github_token
      tags: 
        - ${CI_COMMIT_SHA:0:6}
        - PR-${CI_COMMIT_PULL_REQUEST}
    when:
      event: pull_request

  publish-release:
    image: plugins/docker
    group: docker
    settings:
      dry_run: false
      repo: ghcr.io/${CI_REPO}
      registry: ghcr.io
      dockerfile: Dockerfile.multistage
      platforms: linux/amd64
      build_args:
        - VERSION=${CI_COMMIT_TAG##v}
        - SERVICE=${CI_REPO_NAME}
        - GITHUB_LOGIN=${GITHUB_USERNAME}
        - GITHUB_PASSWORD=${GITHUB_TOKEN}
      username:
        from_secret: github_username
      password: 
        from_secret: github_token
      tags: 
        - ${CI_COMMIT_SHA:0:6}
        - ${CI_COMMIT_TAG##v}
        - latest
    when:
      event: 
        - tag